#This is config.yml for plugin RulesUI.

#This PLUGIN and CONFIG created by Hrasek1000.
#When do you find problem, please write on my mail. hrasek1000@gmail.com

#Here write title. Example: Rules
Title: "Rules"
#Here write rules of your server.
Line1: "1."
Line2: "2."
Line3: "3."
Line4: "4."
Line5: "5."
Line6: "6."
Line7: "7."
Line8: "8."
Line9: "9."
Line10: "10."
